# SERVICE CONFIGURATION
apiVersion: v1
kind: Service
metadata:
  name: diginext-svc
  namespace: diginext
  labels:
    app: diginext
spec:
  # type: NodePort
  ports:
    - port: 6969
  selector:
    app: diginext
---
# POD DEPLOYMENT CONFIGURATION
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diginext
  namespace: diginext
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: diginext
  template:
    metadata:
      labels:
        app: diginext
    spec:
      containers:
        - name: diginext
          image: digitop/diginext:latest
          ports:
            - containerPort: 6969
          securityContext:
            # this is required for Docker but very dangerous !
            privileged: true
            runAsUser: 0
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: PORT
              value: "6969"
            - name: NODE_ENV
              value: production
            - name: CLI_MODE
              value: server
            - name: DEV_MODE
              value: "false"
            - name: BASE_URL
              value: https://api.diginext.site
            - name: MONGODB_CONNECTION_STRING
              value: 
            - name: JWT_SECRET
              value: 
            - name: JWT_EXPIRE_TIME
              value: 48h
            - name: GOOGLE_CLIENT_ID
              value: 
            - name: GOOGLE_CLIENT_SECRET
              value: 
            - name: LOG_DIR
              value: /usr/diginext/public/logs
            - name: BUILDER
              value: docker
          volumeMounts:
            # this is required for Docker but very dangerous !
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: storage
              mountPath: /var/app/storage
            - name: logs
              mountPath: /usr/diginext/public/logs
            - name: home
              mountPath: /root
      volumes:
        # this is required for Docker but very dangerous !
        - name: docker-sock
          hostPath:
            path: "/var/run/docker.sock"
        - name: storage
          hostPath:
            path: /home/dev/diginext/storage
        - name: logs
          hostPath:
            path: /home/dev/diginext/public/logs
        - name: home
          hostPath:
            path: /home/dev/diginext/storage/home

