# MONGODB STANDALONE VERSION
version: "3"
volumes:
    mongo:
services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - '27017:27017'
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=diginext
        volumes:
            - mongo:/data/db
