version: "3"
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: diginext-mongo
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=diginext
        image: mongo
        volumes:
            - ./storage/mongo:/data/db
    diginext:
        container_name: diginext
        depends_on:
            - mongo
        build:
            context: .
            dockerfile: Dockerfile.dev
        working_dir: /usr/app/
        ports:
            - "6969:6969"
        volumes:
            # HOST:CONTAINER
            - "/var/run/docker.sock:/var/run/docker.sock"
            - ./dist:/usr/diginext-cli/dist
            - ./public:/usr/diginext-cli/public
            - ./storage:/var/app/storage
        environment:
            - NODE_ENV=development
            - PORT=6969
            - BASE_URL=http://localhost:6969
            - MONGODB_CONNECTION_STRING=mongodb://root:diginext@mongo:27017/digirelease?authSource=admin
            - CLI_MODE=server
            - JWT_SECRET=
            - JWT_EXPIRE_TIME=48h
            - GOOGLE_CLIENT_ID=
            - GOOGLE_CLIENT_SECRET=
            - PROJECT_DIR=/usr/app/deploy
            - STORAGE=/var/app/storage
