apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: diginext
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    gitCommit: 
      ignoreChanges: true
  artifacts:
    - image: digitop/diginext
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
deploy:
  kubeContext: topgroup-k3s
