apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: diginext-cli
build:
  artifacts:
    - image: digitop/diginext-cli
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
deploy:
  kubeContext: topgroup-k3s
