import authCluster from "./cluster-auth";
import { createImagePullSecretsInNamespace } from "./image-pull-secret";
import { currentCluster, currentContext, getKubeConfig, getKubeContextByCluster, getKubeContextByClusterShortName } from "./kube-config";
import { previewPrerelease, rollout } from "./kube-deploy";
import {
	createNamespace,
	deleteDeploy,
	deleteDeploymentsByFilter,
	deleteEnvVar,
	deleteEnvVarByFilter,
	deleteIngress,
	deleteIngressByFilter,
	deleteNamespace,
	deleteNamespaceByCluster,
	deleteSecret,
	deleteSecretsByFilter,
	deleteService,
	deleteServiceByFilter,
	getAllDeploys,
	getAllIngresses,
	getAllNamespaces,
	getAllPods,
	getAllSecrets,
	getAllServices,
	getDeploy,
	getDeploys,
	getDeploysByFilter,
	getIngress,
	getPod,
	getPodsByFilter,
	getService,
	isNamespaceExisted,
	isSecretExisted,
	kubectlApply,
	kubectlApplyContent,
	logPod,
	logPodByFilter,
	setDeployImage,
	setDeployImageByFilter,
	setDeployImagePullSecretByFilter,
	setEnvVar,
	setEnvVarByFilter,
} from "./kubectl";
import { checkCertManagerInstalled, checkNginxIngressInstalled } from "./stack-check";
import { installCertManagerStack, installNginxIngressStack } from "./stack-install";

const ClusterManager = {
	// cluster-helpers
	authCluster,
	createImagePullSecretsInNamespace,
	currentContext,
	currentCluster,
	// kube-helpers
	createNamespace,
	deleteNamespace,
	deleteNamespaceByCluster,
	deleteSecret,
	deleteDeploy,
	deleteDeploymentsByFilter,
	deleteEnvVar,
	deleteEnvVarByFilter,
	deleteIngressByFilter,
	deleteIngress,
	deleteSecretsByFilter,
	deleteService,
	deleteServiceByFilter,
	getKubeConfig,
	getKubeContextByClusterShortName,
	getKubeContextByCluster,
	getDeploys,
	getAllServices,
	getAllIngresses,
	getAllPods,
	getAllDeploys,
	getAllSecrets,
	getAllNamespaces,
	getService,
	getPod,
	getPodsByFilter,
	getDeploysByFilter,
	getIngress,
	getDeploy,
	logPod,
	logPodByFilter,
	isNamespaceExisted,
	isSecretExisted,
	setEnvVar,
	setEnvVarByFilter,
	setDeployImage,
	setDeployImageByFilter,
	setDeployImagePullSecretByFilter,
	// deploy
	previewPrerelease,
	rollout,
	kubectlApply,
	kubectlApplyContent,
	// stacks
	checkCertManagerInstalled,
	checkNginxIngressInstalled,
	installCertManagerStack,
	installNginxIngressStack,
};

export default ClusterManager;
