version: "3"
services:
  redis-server:
    image: "redis"
    volumes:
      - ./redis_data:/data
  diginext-cli:
    image: "digitop/diginext-cli:{{version}}"
    depends_on:
      - redis-server
    working_dir: /usr/app/
    ports:
      - "6969:6969"
      - "7070:7070"
    restart: unless-stopped
    command:
      - /bin/bash
      - -c
      - |
        /usr/diginext-cli/auth.sh
        node /usr/diginext-cli/index.js
    volumes: # HOST:CONTAINER
      - /Users/duynguyen/www/build_cli:/usr/app/deploy
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./keys:/keys
      - ./public:/usr/diginext-cli/public
    environment:
      - CLI_MODE=server
      - PROJECT_DIR=/usr/app/deploy
      - PORT=6969
      - SOCKET_PORT=7070
      - SOCKET_BASE_URL=wss://deploy.digitop.vn
# docker run --mount type=bind,source="$(pwd)",target=/usr/app/deploy --mount type=bind,source="/var/run/docker.sock",target=/var/run/docker.sock digitop/diginext-cli
