name: Test Workflow

# TRIGGERS
on:
  push:
    branches:
      - '*'             # matches every branch that doesn't contain a '/'
      - '*/*'           # matches every branch containing a single '/'
      - '**'            # matches every branch
      - "!main"         # exclude "main"
      - "!beta"         # exclude "beta"
      - "!prerelease"   # exclude "prerelease"

# ENVIRONMENT VARIABLES
env:
  DB_URI: mongodb://localhost:27017
  CLI_MODE: server
  BUILDER: podman
  PORT: 6969
  BASE_URL: http://localhost:6969
  JWT_SECRET: J9xjKudq5p6dNopGHExnRv5zIB4vo6aX3z3mdrPJPJSYqB4jIA8z5ftLmKz03boo
  TEST_BITBUCKET_ORG: ${{ vars.TEST_BITBUCKET_ORG }}
  TEST_BITBUCKET_USERNAME: ${{ vars.TEST_BITBUCKET_USERNAME }}
  TEST_BITBUCKET_APP_PASS: ${{ secrets.TEST_BITBUCKET_APP_PASS }}
  TEST_DOCKERHUB_USER: ${{ vars.TEST_DOCKERHUB_USER }}
  TEST_DOCKERHUB_PASS: ${{ secrets.TEST_DOCKERHUB_PASS }}
  TEST_DO_CLUSTER_NAME: ${{ vars.TEST_DO_CLUSTER_NAME }}
  TEST_DO_API_TOKEN: ${{ secrets.TEST_DO_API_TOKEN }}
  TEST_GCLOUD_CLUSTER_NAME: ${{ vars.TEST_GCLOUD_CLUSTER_NAME }}
  TEST_GCLOUD_SERVICE_ACCOUNT: ${{ secrets.TEST_GCLOUD_SERVICE_ACCOUNT }}
  TEST_GITHUB_PAT: ${{ secrets.TEST_GITHUB_PAT }}
  TEST_METAL_CLUSTER_NAME: ${{ vars.TEST_METAL_CLUSTER_NAME }}
  TEST_METAL_CLUSTER_KUBECONFIG: ${{ secrets.TEST_METAL_CLUSTER_KUBECONFIG }}

# CI/CD STEPS
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'ci(') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install package dependencies
      #   run: npm ci
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm test